---
title: "BS_730_Project_exploration"
author: "Luke Wilsen"
date: "2024-11-07"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(RSocrata)
df <- read.socrata(
  url = "https://data.cdc.gov/resource/n8mc-b4w4.json?$limit=50000"
)
```

```{r}
head(df)
```

# Research Question
Can we predict hospitalization outcomes based on 
• Age group
• Sex
• Race
• Ethnicity
• Exposure
• Symptom Status
• Underlying Conditions

```{r}
unique(df$race)

df %>% 
  filter(race %in% c("Black", "Multiple/Other" , "White", "American Indian/Alaska Native", "Asian"), hosp_yn %in% c("No", "Yes")) %>% 
  ggplot()+
  geom_bar(aes(x = race, fill = hosp_yn), position = "dodge")
```

```{r}
df %>% 
  filter( hosp_yn %in% c("No", "Yes")) %>% 
  ggplot()+
  geom_bar(aes(x = age_group, fill = hosp_yn), position = "dodge")
```

Age clearly has a very strong correlation with hospitalization
- You can tell from the high proportion of 50+ who were hospitalized compared to those proportions of people under 50

```{r}
df %>% 
  filter(race != "NA", race != "Unknown", race != "Missing") %>% 
  ggplot()+
  geom_bar(aes(x = age_group, fill = race), position = "dodge")
```




